import { TabWidget, DatePickerPopup, TimePickerPopup, Time, Date, Button, VerticalBox, HorizontalBox, CheckBox, LineEdit } from "std-widgets.slint";
import { CustomButton } from "custom-button.slint";

component LoginModal inherits Rectangle {
    height: 400px;
    width: 500px;
    background: #f8fafc;
    border-color: #e2e8f0;
    border-width: 1px;
    border-radius: 12px;
    padding: 20px;

    property <bool> loginValid: login_name.text != "";
    property <bool> passValid: passw.text != "";

    property <bool> new_usernameValid: registration_username.text != "";
    property <bool> new_passValid: newpassw.text != "";
    property <bool> new_nameValid: registration-name.text != "";
    property <bool> new_surnameValid: registration-surname.text != "";

    property <bool> staticFormValid: loginValid && passValid;
    property <bool> registrationFormValid: new_usernameValid && new_passValid && new_nameValid && new_surnameValid;

    callback collect-login(login: string, password: string);
    callback collect-registration(name: string, surname: string, username: string, password: string);

    TabWidget {
        width: 100%;
        height: 100%;

        Tab {
            title: "Login";
            VerticalBox {
                width: 100%;
                height: 100%;
                padding: 20px;
                spacing: 50px;
                y: 50px;

                VerticalBox {
                    padding: 0;
                    Rectangle {
                        padding: 0;
                        width: 100%;
                        height: 40px;

                        drop-shadow-color: loginValid ? #2E3445 : red;
                        drop-shadow-blur: 8px;
                        border-color: #2E3445;
                        border-width: 1px;

                        login-name := LineEdit {
                            font-size: 14px;
                            width: parent.width;
                            height: parent.height;
                            placeholder-text: "Login";
                        }
                    }

                    Rectangle {
                        padding: 0;
                        width: 100%;
                        height: 40px;

                        drop-shadow-color: passValid ? #2E3445 : red;
                        drop-shadow-blur: 8px;
                        border-color: #2E3445;
                        border-width: 1px;

                        passw := LineEdit {
                            font-size: 14px;
                            width: parent.width;
                            height: parent.height;
                            placeholder-text: "Password";
                        }
                    }
                }

                HorizontalBox {
                    alignment: end;
                    padding: 0;
                    padding-top: 20px;
                    width: 100%;
                    CustomButton {
                        text: "Reset";
                        width: 100px;
                        height: 36px;
                        background: #2E3445;
                        color: #D5E2FA;
                        mouse-cursor: pointer;
                        clicked => {
                            passw.text = "";
                            login-name.text = "";
                        }
                    }

                    CustomButton {
                        text: "Log In";
                        width: 100px;
                        height: 36px;
                        enabled: staticFormValid;
                        background: staticFormValid ? #2E3445 : #D5E2FA;
                        color: staticFormValid ? #D5E2FA : #2e344585;
                        mouse-cursor: pointer;
                        clicked => {
                            collect-login(
                                login-name.text,
                                passw.text);
                        }
                    }
                }
            }
        }

        Tab {
            title: "Registration";
            VerticalBox {
                width: 100%;
                height: 100%;
                padding: 20px;
                spacing: 50px;
                y: 50px;

                VerticalBox {
                    padding: 0;
                    Rectangle {
                        padding: 0;
                        width: 100%;
                        height: 40px;

                        drop-shadow-color: new_nameValid ? #2E3445 : red;
                        drop-shadow-blur: 8px;
                        border-color: #2E3445;
                        border-width: 1px;

                        registration-name := LineEdit {
                            font-size: 14px;
                            width: parent.width;
                            height: parent.height;
                            placeholder-text: "Name";
                        }
                    }

                    Rectangle {
                        padding: 0;
                        width: 100%;
                        height: 40px;

                        drop-shadow-color: new_surnameValid ? #2E3445 : red;
                        drop-shadow-blur: 8px;
                        border-color: #2E3445;
                        border-width: 1px;

                        registration-surname := LineEdit {
                            font-size: 14px;
                            width: parent.width;
                            height: parent.height;
                            placeholder-text: "Surname";
                        }
                    }

                    Rectangle {
                        padding: 0;
                        width: 100%;
                        height: 40px;

                        drop-shadow-color: new_usernameValid ? #2E3445 : red;
                        drop-shadow-blur: 8px;
                        border-color: #2E3445;
                        border-width: 1px;

                        registration-username := LineEdit {
                            font-size: 14px;
                            width: parent.width;
                            height: parent.height;
                            placeholder-text: "New Login";
                        }
                    }

                    Rectangle {
                        padding: 0;
                        width: 100%;
                        height: 40px;

                        drop-shadow-color: new_passValid ? #2E3445 : red;
                        drop-shadow-blur: 8px;
                        border-color: #2E3445;
                        border-width: 1px;

                        newpassw := LineEdit {
                            font-size: 14px;
                            width: parent.width;
                            height: parent.height;
                            placeholder-text: "Password";
                        }
                    }
                }

                HorizontalBox {
                    alignment: end;
                    padding: 0;
                    padding-top: 20px;
                    width: 100%;
                    CustomButton {
                        text: "Reset";
                        width: 100px;
                        height: 36px;
                        background: #2E3445;
                        color: #D5E2FA;
                        mouse-cursor: pointer;
                        clicked => {
                            newpassw.text = "";
                            registration-username.text = "";
                            registration-surname.text = "";
                            registration-name.text = "";
                        }
                    }

                    CustomButton {
                        text: "Create user";
                        width: 100px;
                        height: 36px;
                        enabled: registrationFormValid;
                        background: registrationFormValid ? #2E3445 : #D5E2FA;
                        color: registrationFormValid ? #D5E2FA : #2e344585;
                        mouse-cursor: pointer;
                        clicked => {
                            collect-registration(
                                registration_name.text,
                                registration_surname.text,
                                registration_username.text,
                                newpassw.text);
                        }
                    }
                }
            }
        }
    }
}

export { LoginModal }
