import { TabWidget, Time, Date, Button, VerticalBox, HorizontalBox, CheckBox, LineEdit } from "std-widgets.slint";
import { CustomButton } from "custom-button.slint";
import { StaticEventModal } from "events/static-events.modal.slint";

component SelectedWeekdays inherits GridLayout {
    padding: 0;
    spacing-horizontal: 10px;
    spacing-vertical: 5px;
    height: 70px;

    Row {
        Rectangle {
            padding: 0;
            Text {
                text: "Mo";
                font-size: 14px;
                color: #2E3445;
            }
        }

        Rectangle {
            padding: 0;
            Text {
                text: "Tu";
                font-size: 14px;
                color: #2E3445;
            }
        }

        Rectangle {
            padding: 0;
            Text {
                text: "We";
                font-size: 14px;
                color: #2E3445;
            }
        }

        Rectangle {
            padding: 0;
            Text {
                text: "Th";
                font-size: 14px;
                color: #2E3445;
            }
        }

        Rectangle {
            padding: 0;
            Text {
                text: "Fr";
                font-size: 14px;
                color: #2E3445;
            }
        }

        Rectangle {
            padding: 0;
            Text {
                text: "Sa";
                font-size: 14px;
                color: #2E3445;
            }
        }

        Rectangle {
            padding: 0;
            Text {
                text: "Su";
                font-size: 14px;
                color: #2E3445;
            }
        }
    }

    Row {
        Rectangle {
            padding: 0;
            CheckBox {
                padding: 0;
                checked: true;
            }
        }

        Rectangle {
            padding: 0;
            CheckBox {
                padding: 0;
                checked: true;
            }
        }

        Rectangle {
            padding: 0;
            CheckBox {
                padding: 0;
                checked: true;
            }
        }

        Rectangle {
            padding: 0;
            CheckBox {
                padding: 0;
                checked: true;
            }
        }

        Rectangle {
            padding: 0;
            CheckBox {
                padding: 0;
                checked: true;
            }
        }

        Rectangle {
            padding: 0;
            CheckBox {
                padding: 0;
                checked: true;
            }
        }

        Rectangle {
            padding: 0;
            CheckBox {
                padding: 0;
                checked: true;
            }
        }
    }
}

component ModalWindow inherits Rectangle {
    height: 100%;
    width: 100%;
    background: #f8fafc;
    border-color: #e2e8f0;
    border-width: 1px;
    border-radius: 12px;
    padding: 20px;

    drop-shadow-color: #2E3445;
    drop-shadow-blur: 130px;

    in property <Date> selected_date;

    callback collect-static-event-data(name: string, description: string, start_date: Date, end_date: Date, start_time: Time, end_time: Time);
    callback request-close();

    TabWidget {
        width: 100%;
        height: 100%;
        Tab {
            title: "Static";
            StaticEventModal {
                selected_date: selected_date;
                collect-static-event-data(name, description, start_date, end_date, start_time, end_time) => {
                    root.collect-static-event-data(name, description, start_date, end_date, start_time, end_time);
                }
                request-close() => {
                    root.request-close();
                }
            }
        }

        Tab {
            title: "Dynamic";
            VerticalBox {
                width: 100%;
                height: 100%;
                padding: 16px;
                spacing: 24px;

                Text {
                    text: "Dynamic content goes here";
                    font-size: 18px;
                    font-weight: 500;
                    color: #2E3445;
                }

                HorizontalBox {
                    padding: 0;
                    spacing: 20px;
                    alignment: start;
                    Rectangle {
                        padding: 0;
                        Text {
                            padding: 0;
                            text: "Select preferred weekdays:";
                            font-size: 18px;
                            font-weight: 500;
                            color: #2E3445;
                        }
                    }

                    Rectangle {
                        padding: 0;
                        SelectedWeekdays {
                            padding: 0;
                        }
                    }
                }
            }
        }
    }
}

export { ModalWindow }
