import { VerticalBox, HorizontalBox, GridBox, Button, Date, Time } from "std-widgets.slint";
import { ModalWindow } from "modal-window.slint";
import { CustomButton } from "custom-button.slint";

struct SlintDay {
  id: string,
  day-number: int,
  is_today: bool,
  is_selected: bool}

component DayCell inherits Rectangle {
    in property <int> day-number;
    in property <string> date-id;
    in property <bool> is_selected;
    in property <bool> is_today;

    property <bool> hover <=> ta.has-hover;

    callback select_date(string);

    background: #ffffff;
    border-width: 1px;
    border-color: #e0e0e0;
    padding: 0;

    VerticalBox {
        padding: 3px;
        Rectangle {
            padding: 0;
            background: root.hover ? #f1f2fd : #fff;
            animate background {
                duration: 200ms;
                easing: ease-in-out;
            }

            Rectangle {
                height: 35px;
                width: 35px;
                y: 0;
                x: parent.width - self.width;
                background: is_selected ? #5a60ee : (is_today ? #b6b7e4 : transparent);
                animate background {
                    duration: 200ms;
                    easing: ease-in-out;
                }
                border-radius: 8px;
                Text {
                    text: day-number > 0 ? day-number : "";
                    horizontal-alignment: right;
                    padding: 5px;
                    color: is_selected ? #fff : #000;
                    font-size: 14px;
                    font-weight: is_selected ? 600 : 400;
                }
            }
        }
    }

    ta := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            if (day-number > 0) {
                root.select_date(date-id);
            }
        }
    }

    states [
        hovered when root.hover: {}
    ]
}

component CalendarTemplate inherits Rectangle {
    in property <[string]> day-names: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
    in property <[[SlintDay]]> weeks;
    in property <string> date_title;
    callback next-month;
    callback previous-month;
    callback select_date(string);

    height: 90%;
    padding: 0;

    VerticalBox {
        spacing: 0;
        padding: 0;
    
    // Month header
    Rectangle {
            background: white;
            padding: 0;
            width: 100%;
            height: 50px;

            HorizontalBox {
                spacing: 0;
                padding: 0;
                CustomButton {
                    text: "◀"; 
                    width: 50px;
                    height: 50px;
                    clicked => {
                        root.previous-month();
                    }
                }

                Text {
                    text: root.date_title;
                    font-size: 24px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    color: #5A60EE;
                    font-weight: 600;
                }

                CustomButton {
                    text: "▶"; 
                    width: 50px;
                    height: 50px;
                    clicked => {
                        root.next-month();
                    }
                }
            }
        }

    // Weekday headers
    HorizontalBox {
            height: 30px;
            width: 100%;
            spacing: 0;
            padding: 0;
            for day in day-names: Rectangle {
                background: #fff;
                Text {
                    text: day;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    color: #2E3445;
                    font-weight: 800;
                }
            }
        }

        VerticalBox {
            width: 100%;
            spacing: 0;
            padding: 0;
            for week in weeks: HorizontalBox {
                spacing: 0;
                padding: 0;
                for day[i] in week: DayCell {
                    width: 14.28%;
                    day-number: day.day-number;
                    is_selected: day.is_selected;
                    is_today: day.is_today;
                    select_date => {
                        root.select_date(day.id);
                    }
                }
            }
        }
    }
}

component SelectedDateSidebar inherits Rectangle {
    in property <string> selected_date;

    width: 25%;
    height: 100%;
    background: #2E3445;

    HorizontalBox {
        Text {
            text: "Selected Date:";
            font-size: 20px;
            color: #D5E2FA;
        }

        Text {
            text: selected_date;
            font-size: 18px;
            color: #D5E2FA;
        }
    }
}

component ActionsMenu inherits Rectangle {
    callback collect-static-event-data(name: string, description: string, start_date: Date, end_date: Date, start_time: Time, end_time: Time);
    background: #fff;
    padding: 0;

    popup := PopupWindow {
        close-policy: close-on-click-outside;

        ModalWindow {
            request-close => {
                popup.close(); // Close when requested
            }
            collect-static-event-data(name, description, start_date, end_date, start_time, end_time) => {
                root.collect-static-event-data(name, description, start_date, end_date, start_time, end_time);
            }
            padding: 0;
        }

        x: 200px;
        y: 180px;
        height: 600px;
        width: 700px;
    }

    HorizontalBox {
        spacing: 0;
        padding: 5px;

        CustomButton {
            text: "+";
            width: 40px;
            height: 20px;

            clicked => {
                popup.show();
            }
        }
    }
}

export component CalendarWindow inherits Window {
    preferred-width: 1200px;
    preferred-height: 1000px;
    full-screen: true;
    padding: 0;
    padding-left: 2px;
    background: #dddee2;

    in property <[string]> day-names: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
    in property <[[SlintDay]]> weeks;
    in property <string> date_title;
    in property <string> selected_date;
    callback next-month;
    callback previous-month;
    callback select_date(string);
    callback collect_static(name: string, description: string, start_date: Date, end_date: Date, start_time: Time, end_time: Time);

    HorizontalBox {
        width: 100%;
        height: 100%;
        padding: 0;
        spacing: 3px;

        SelectedDateSidebar {
            selected_date: root.selected_date;
        }

        VerticalBox {
            spacing: 3px;
            padding: 0;
            height: 100%;
            width: 75%;

            ActionsMenu {
                height: 60px;
                padding: 0;
                collect-static-event-data(name, description, start_date, end_date, start_time, end_time) => {
                    root.collect_static(name, description, start_date, end_date, start_time, end_time);
                }
            }

            CalendarTemplate {
                height: parent.height - 60px;
                day-names: root.day-names;
                weeks: root.weeks;
                date_title: root.date_title;
                background: #fff;
                next-month => {
                    root.next-month();
                }
                previous-month => {
                    root.previous-month();
                }
                select_date(date) => {
                    root.select_date(date);
                }
            }
        }
    }
}
